// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// Load .env.local first (takes priority), then fall back to .env
config({ path: ".env.local", override: false });
config({ path: ".env", override: false });

export default {
  schema: "prisma/schema.prisma",
};
